extends "res://Scripts/Database.gd"

const Jacket_M88 = preload("res://Items/Clothing/Jacket_M88/Jacket_M88.tscn")
const Jacket_FJ = preload("res://Items/Clothing/Jacket_FJ/Jacket_FJ.tscn")
const Jacket_M81 = preload("res://Items/Clothing/Jacket_M81/Jacket_M81.tscn")
const Helmet_Wz63 = preload("res://Items/Helmets/Helmet_Wz63/Helmet_Wz63.tscn")
const Balaclava = preload("res://Items/Clothing/Balaclava/Balaclava.tscn")
const Vest_FJ_Armored = preload("res://Items/Rigs/Vest_FJ_Armored/Vest_FJ_Armored.tscn")
const Vest_FJ = preload("res://Items/Rigs/Vest_FJ/Vest_FJ.tscn")
const Colt_727 = preload("res://Items/Weapons/Colt_727/Colt_727.tscn")
const Colt_727_Rig = preload("res://Items/Weapons/Colt_727/Colt_727_Rig.tscn")
const Pants_FJ = preload("res://Items/Clothing/Pants_FJ/Pants_FJ.tscn")
const Pants_M88 = preload("res://Items/Clothing/Pants_M88/Pants_M88.tscn")
const Pants_M81 = preload("res://Items/Clothing/Pants_M81/Pants_M81.tscn")
const Boots_FJ = preload("res://Items/Clothing/Boots_FJ/Boots_FJ.tscn")
const Boots_Jungle = preload("res://Items/Clothing/Boots_Jungle/Boots_Jungle.tscn")
const Vest_Lifchik = preload("res://Items/Rigs/Vest_Lifchik/Vest_Lifchik.tscn")
const TG_Faust = preload("res://Items/Rigs/TG_Faust/TG_Faust.tscn")
const Vest_6B5 = preload("res://Items/Rigs/Vest_6B5/Vest_6B5.tscn")
const Gloves_Nomex = preload("res://Items/Clothing/Gloves_Nomex/Gloves_Nomex.tscn")
const Gloves_Knit = preload("res://Items/Clothing/Gloves_Knit/Gloves_Knit.tscn")
const Gloves_Soviet = preload("res://Items/Clothing/Gloves_Soviet/Gloves_Soviet.tscn")